/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.utfpr.clubsgestor;

/**
 *
 * @author jeferson.scarsi
 */
public class Financeiro extends javax.swing.JInternalFrame {

    /**
     * Creates new form ContasPagar
     */
    public Financeiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        rbtContasPagar = new javax.swing.JRadioButton();
        rbtContasReceber = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNumTitulo = new javax.swing.JTextField();
        txtCodCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNomeFantasia = new javax.swing.JTextField();
        txtDataCompetencia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rbtContasPagarLanc = new javax.swing.JRadioButton();
        rbtContasReceberLanc = new javax.swing.JRadioButton();
        txtDataVenc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtValorBruto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cboFormaPagamento = new javax.swing.JComboBox<>();
        cboParcela = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Contas a Pagar");

        jLabel1.setText("Cód. Sócios: ");

        jLabel2.setText("Num. Título:");

        jButton1.setText("Pesquisar");

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód. Título", "Cód. Sócio", "Nome Sócio", "Num. Sequencia", "Valor Bruto", "Valor Desconto", "Valor Acrescimo", "Valor Líquido"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        buttonGroup1.add(rbtContasPagar);
        rbtContasPagar.setSelected(true);
        rbtContasPagar.setText("Contas a Pagar");

        buttonGroup1.add(rbtContasReceber);
        rbtContasReceber.setText("Contas a Receber");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rbtContasPagar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rbtContasReceber)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(175, 175, 175))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addComponent(rbtContasPagar))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(rbtContasReceber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        jTabbedPane2.addTab("Pesquisar", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Informações de Pagamento");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel4.setText("Parcela:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 110, -1));

        jLabel5.setText("Num. Título:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 37, -1, -1));

        txtNumTitulo.setEditable(false);
        jPanel2.add(txtNumTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 57, 75, -1));
        jPanel2.add(txtCodCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 57, 75, -1));

        jLabel6.setText("Nome Fantasia:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 83, -1, -1));
        jPanel2.add(txtNomeFantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 230, -1));
        jPanel2.add(txtDataCompetencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 110, -1));

        jLabel7.setText("Data Competencia:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 95, -1));

        buttonGroup2.add(rbtContasPagarLanc);
        rbtContasPagarLanc.setSelected(true);
        rbtContasPagarLanc.setText("Contas a Pagar");
        jPanel2.add(rbtContasPagarLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 53, -1, -1));

        buttonGroup2.add(rbtContasReceberLanc);
        rbtContasReceberLanc.setText("Contas a Receber");
        jPanel2.add(rbtContasReceberLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 53, -1, -1));
        jPanel2.add(txtDataVenc, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 100, 100, -1));

        jLabel8.setText("Data Vencimento:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 83, -1, -1));
        jPanel2.add(txtValorBruto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 149, 110, -1));

        jLabel9.setText("Valor Bruto:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 129, 75, -1));
        jPanel2.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 149, 110, -1));

        jLabel10.setText("Valor Desconto:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 129, 92, -1));
        jPanel2.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 149, 110, -1));

        jLabel11.setText("Valor Acréscimo:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 129, 92, -1));

        jTextField11.setEditable(false);
        jPanel2.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 149, 110, -1));

        jLabel12.setText("Valor Líquido:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 129, 92, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setText("Dados do Cliente");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel14.setText("Cód. Cliente:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 37, 75, -1));

        cboFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Dinheiro", "Cartão de Crédito", "Cartão de Débito", "Cheque" }));
        jPanel2.add(cboFormaPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 200, -1));

        cboParcela.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cboParcela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cboParcelaKeyReleased(evt);
            }
        });
        jPanel2.add(cboParcela, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 100, -1));

        jLabel15.setText("Forma de Pagamento:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 110, -1));

        jButton3.setText("Salvar");
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, -1, -1));

        jButton4.setText("Cancelar");
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, -1, -1));

        jTabbedPane2.addTab("Lançamentos", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cboParcelaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboParcelaKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cboParcelaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cboFormaPagamento;
    private javax.swing.JComboBox<String> cboParcela;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JRadioButton rbtContasPagar;
    private javax.swing.JRadioButton rbtContasPagarLanc;
    private javax.swing.JRadioButton rbtContasReceber;
    private javax.swing.JRadioButton rbtContasReceberLanc;
    private javax.swing.JTextField txtCodCliente;
    private javax.swing.JTextField txtDataCompetencia;
    private javax.swing.JTextField txtDataVenc;
    private javax.swing.JTextField txtNomeFantasia;
    private javax.swing.JTextField txtNumTitulo;
    private javax.swing.JTextField txtValorBruto;
    // End of variables declaration//GEN-END:variables
}
