/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.utfpr.clubsgestor;

/**
 *
 * @author jeferson.scarsi
 */
public class Financeiro extends javax.swing.JInternalFrame {

    /**
     * Creates new form ContasPagar
     */
    public Financeiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodSocioPesq = new javax.swing.JTextField();
        lblNumTitulo = new javax.swing.JLabel();
        txtNumTituloPesq = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTituloPesq = new javax.swing.JTable();
        optContasPagarPesq = new javax.swing.JRadioButton();
        optContasReceberPesq = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        lblInfPagLanc = new javax.swing.JLabel();
        lblParcela = new javax.swing.JLabel();
        lblNumTituloLanc = new javax.swing.JLabel();
        txtNumTituloLanc = new javax.swing.JTextField();
        txtCodClienteLanc = new javax.swing.JTextField();
        lblNomeFantasiaLanc = new javax.swing.JLabel();
        txtNomeFantasiaLanc = new javax.swing.JTextField();
        txtDataCompetenciaLanc = new javax.swing.JTextField();
        lblDataCompLanc = new javax.swing.JLabel();
        optContasPagarLanc = new javax.swing.JRadioButton();
        optContasReceberLanc = new javax.swing.JRadioButton();
        txtDataVencLanc = new javax.swing.JTextField();
        lblDataVencLanc = new javax.swing.JLabel();
        txtValorBrutoLanc = new javax.swing.JTextField();
        lblValorBrutoLanc = new javax.swing.JLabel();
        txtValorDescLanc = new javax.swing.JTextField();
        lblValorDescLanc = new javax.swing.JLabel();
        txtValorAcrescimoLanc = new javax.swing.JTextField();
        lblValorAcrescimoLanc = new javax.swing.JLabel();
        txtValorLiqLanc = new javax.swing.JTextField();
        lblValorLiqLanc = new javax.swing.JLabel();
        lblDadosCliente = new javax.swing.JLabel();
        lblCodClienteLanc = new javax.swing.JLabel();
        cmbFormaPagamento = new javax.swing.JComboBox<>();
        cmbParcela = new javax.swing.JComboBox<>();
        lblFormaPagLanc = new javax.swing.JLabel();
        btnSalvarLanc = new javax.swing.JButton();
        btnCancelarLanc = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Financeiro");

        jLabel1.setText("Cód. Sócios: ");

        lblNumTitulo.setText("Num. Título:");

        btnPesquisar.setText("Pesquisar");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tblTituloPesq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód. Título", "Cód. Sócio", "Nome Sócio", "Num. Sequencia", "Valor Bruto", "Valor Desconto", "Valor Acrescimo", "Valor Líquido"
            }
        ));
        jScrollPane1.setViewportView(tblTituloPesq);

        buttonGroup1.add(optContasPagarPesq);
        optContasPagarPesq.setSelected(true);
        optContasPagarPesq.setText("Contas a Pagar");

        buttonGroup1.add(optContasReceberPesq);
        optContasReceberPesq.setText("Contas a Receber");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodSocioPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(optContasPagarPesq))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNumTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumTituloPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(optContasReceberPesq)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(175, 175, 175))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtCodSocioPesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPesquisar))
                    .addComponent(optContasPagarPesq))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumTitulo)
                    .addComponent(txtNumTituloPesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar)
                    .addComponent(optContasReceberPesq))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        jTabbedPane2.addTab("Pesquisar", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInfPagLanc.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblInfPagLanc.setText("Informações de Pagamento");
        jPanel2.add(lblInfPagLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        lblParcela.setText("Parcela:");
        jPanel2.add(lblParcela, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 110, -1));

        lblNumTituloLanc.setText("Num. Título:");
        jPanel2.add(lblNumTituloLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 37, -1, -1));

        txtNumTituloLanc.setEditable(false);
        jPanel2.add(txtNumTituloLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 57, 75, -1));
        jPanel2.add(txtCodClienteLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 57, 75, -1));

        lblNomeFantasiaLanc.setText("Nome Fantasia:");
        jPanel2.add(lblNomeFantasiaLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 83, -1, -1));
        jPanel2.add(txtNomeFantasiaLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 230, -1));
        jPanel2.add(txtDataCompetenciaLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 110, -1));

        lblDataCompLanc.setText("Data Competencia:");
        jPanel2.add(lblDataCompLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 95, -1));

        buttonGroup2.add(optContasPagarLanc);
        optContasPagarLanc.setSelected(true);
        optContasPagarLanc.setText("Contas a Pagar");
        optContasPagarLanc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                optContasPagarLancKeyReleased(evt);
            }
        });
        jPanel2.add(optContasPagarLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 53, -1, -1));

        buttonGroup2.add(optContasReceberLanc);
        optContasReceberLanc.setText("Contas a Receber");
        jPanel2.add(optContasReceberLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 53, -1, -1));
        jPanel2.add(txtDataVencLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 100, 100, -1));

        lblDataVencLanc.setText("Data Vencimento:");
        jPanel2.add(lblDataVencLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 83, -1, -1));
        jPanel2.add(txtValorBrutoLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 149, 110, -1));

        lblValorBrutoLanc.setText("Valor Bruto:");
        jPanel2.add(lblValorBrutoLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 129, 75, -1));
        jPanel2.add(txtValorDescLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 149, 110, -1));

        lblValorDescLanc.setText("Valor Desconto:");
        jPanel2.add(lblValorDescLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 129, 92, -1));
        jPanel2.add(txtValorAcrescimoLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 149, 110, -1));

        lblValorAcrescimoLanc.setText("Valor Acréscimo:");
        jPanel2.add(lblValorAcrescimoLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 129, 92, -1));

        txtValorLiqLanc.setEditable(false);
        jPanel2.add(txtValorLiqLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 149, 110, -1));

        lblValorLiqLanc.setText("Valor Líquido:");
        jPanel2.add(lblValorLiqLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 129, 92, -1));

        lblDadosCliente.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblDadosCliente.setText("Dados do Cliente");
        jPanel2.add(lblDadosCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        lblCodClienteLanc.setText("Cód. Cliente:");
        jPanel2.add(lblCodClienteLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 37, 75, -1));

        cmbFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Dinheiro", "Cartão de Crédito", "Cartão de Débito", "Cheque" }));
        jPanel2.add(cmbFormaPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 200, -1));

        cmbParcela.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cmbParcela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmbParcelaKeyReleased(evt);
            }
        });
        jPanel2.add(cmbParcela, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 100, -1));

        lblFormaPagLanc.setText("Forma de Pagamento:");
        jPanel2.add(lblFormaPagLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 110, -1));

        btnSalvarLanc.setText("Salvar");
        jPanel2.add(btnSalvarLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, -1, -1));

        btnCancelarLanc.setText("Cancelar");
        jPanel2.add(btnCancelarLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, -1, -1));

        jTabbedPane2.addTab("Lançamentos", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cmbParcelaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbParcelaKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbParcelaKeyReleased

    private void optContasPagarLancKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_optContasPagarLancKeyReleased
        // TODO add your handling code here:        
    }//GEN-LAST:event_optContasPagarLancKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarLanc;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvarLanc;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmbFormaPagamento;
    private javax.swing.JComboBox<String> cmbParcela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblCodClienteLanc;
    private javax.swing.JLabel lblDadosCliente;
    private javax.swing.JLabel lblDataCompLanc;
    private javax.swing.JLabel lblDataVencLanc;
    private javax.swing.JLabel lblFormaPagLanc;
    private javax.swing.JLabel lblInfPagLanc;
    private javax.swing.JLabel lblNomeFantasiaLanc;
    private javax.swing.JLabel lblNumTitulo;
    private javax.swing.JLabel lblNumTituloLanc;
    private javax.swing.JLabel lblParcela;
    private javax.swing.JLabel lblValorAcrescimoLanc;
    private javax.swing.JLabel lblValorBrutoLanc;
    private javax.swing.JLabel lblValorDescLanc;
    private javax.swing.JLabel lblValorLiqLanc;
    private javax.swing.JRadioButton optContasPagarLanc;
    private javax.swing.JRadioButton optContasPagarPesq;
    private javax.swing.JRadioButton optContasReceberLanc;
    private javax.swing.JRadioButton optContasReceberPesq;
    private javax.swing.JTable tblTituloPesq;
    private javax.swing.JTextField txtCodClienteLanc;
    private javax.swing.JTextField txtCodSocioPesq;
    private javax.swing.JTextField txtDataCompetenciaLanc;
    private javax.swing.JTextField txtDataVencLanc;
    private javax.swing.JTextField txtNomeFantasiaLanc;
    private javax.swing.JTextField txtNumTituloLanc;
    private javax.swing.JTextField txtNumTituloPesq;
    private javax.swing.JTextField txtValorAcrescimoLanc;
    private javax.swing.JTextField txtValorBrutoLanc;
    private javax.swing.JTextField txtValorDescLanc;
    private javax.swing.JTextField txtValorLiqLanc;
    // End of variables declaration//GEN-END:variables
}
