/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.utfpr.clubsgestor;

import javax.swing.JDesktopPane;

/**
 *
 * @author jeferson.scarsi
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    JDesktopPane desktopPane = new JDesktopPane();
    
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jToolBar1 = new javax.swing.JToolBar();
        btnMenuClube = new javax.swing.JButton();
        btnMenuUsuarios = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        bntMenuSocios = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnMenuContasPagar = new javax.swing.JButton();
        btnMenuContasReceber = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        btnMenuSair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniClube = new javax.swing.JMenuItem();
        mniUsuarios = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniSocios = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniContasPagar = new javax.swing.JMenuItem();
        mniContasReceber = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuRelatorios = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        mniSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        jToolBar1.setRollover(true);

        btnMenuClube.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens-32px/visao-da-empresa.png"))); // NOI18N
        btnMenuClube.setText("Clube");
        btnMenuClube.setFocusable(false);
        btnMenuClube.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenuClube.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMenuClube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuClubeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnMenuClube);

        btnMenuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens-32px/adicionar-usuario.png"))); // NOI18N
        btnMenuUsuarios.setText("Usuários");
        btnMenuUsuarios.setFocusable(false);
        btnMenuUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenuUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMenuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuUsuariosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnMenuUsuarios);
        jToolBar1.add(jSeparator4);

        bntMenuSocios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens-32px/socios.png"))); // NOI18N
        bntMenuSocios.setText("Sócios");
        bntMenuSocios.setFocusable(false);
        bntMenuSocios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntMenuSocios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bntMenuSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMenuSociosActionPerformed(evt);
            }
        });
        jToolBar1.add(bntMenuSocios);
        jToolBar1.add(jSeparator5);

        btnMenuContasPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens-32px/contas-a-pagar.png"))); // NOI18N
        btnMenuContasPagar.setText("Contas a Pagar");
        btnMenuContasPagar.setFocusable(false);
        btnMenuContasPagar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenuContasPagar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMenuContasPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuContasPagarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnMenuContasPagar);

        btnMenuContasReceber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens-32px/contas-a-receber.png"))); // NOI18N
        btnMenuContasReceber.setText("Contas a Receber");
        btnMenuContasReceber.setFocusable(false);
        btnMenuContasReceber.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenuContasReceber.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMenuContasReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuContasReceberActionPerformed(evt);
            }
        });
        jToolBar1.add(btnMenuContasReceber);
        jToolBar1.add(jSeparator9);

        btnMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens-32px/sair.png"))); // NOI18N
        btnMenuSair.setText("Sair");
        btnMenuSair.setFocusable(false);
        btnMenuSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenuSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuSairActionPerformed(evt);
            }
        });
        jToolBar1.add(btnMenuSair);

        jMenu1.setText("Cadastros");

        mniClube.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens-16px/visao-da-empresa.png"))); // NOI18N
        mniClube.setText("Clube");
        mniClube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniClubeActionPerformed(evt);
            }
        });
        jMenu1.add(mniClube);

        mniUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens-16px/adicionar-usuario.png"))); // NOI18N
        mniUsuarios.setText("Usuários");
        mniUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniUsuariosActionPerformed(evt);
            }
        });
        jMenu1.add(mniUsuarios);
        jMenu1.add(jSeparator1);

        mniSocios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens-16px/socios.png"))); // NOI18N
        mniSocios.setText("Sócios");
        mniSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSociosActionPerformed(evt);
            }
        });
        jMenu1.add(mniSocios);
        jMenu1.add(jSeparator2);

        mniSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens-16px/sair.png"))); // NOI18N
        mniSair.setText("Sair");
        mniSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSairActionPerformed(evt);
            }
        });
        jMenu1.add(mniSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Financeiro");

        mniContasPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens-16px/a-pagar.png"))); // NOI18N
        mniContasPagar.setText("Contas Pagar");
        mniContasPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniContasPagarActionPerformed(evt);
            }
        });
        jMenu2.add(mniContasPagar);

        mniContasReceber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens-16px/contas-a-receber.png"))); // NOI18N
        mniContasReceber.setText("Contas Receber");
        mniContasReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniContasReceberActionPerformed(evt);
            }
        });
        jMenu2.add(mniContasReceber);
        jMenu2.add(jSeparator3);

        mnuRelatorios.setText("Relatórios");
        jMenu2.add(mnuRelatorios);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ajuda");

        mniSobre.setText("Sobre");
        jMenu3.add(mniSobre);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 341, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(717, 460));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mniClubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniClubeActionPerformed
        // TODO add your handling code here:
        CadastroClube janela = new CadastroClube();
        janela.setVisible(true);
        
        desktopPane.add(janela);
        this.setContentPane(desktopPane);
    }//GEN-LAST:event_mniClubeActionPerformed

    private void btnMenuClubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuClubeActionPerformed
        // TODO add your handling code here:
        
        CadastroClube janela = new CadastroClube();
        janela.setVisible(true);
        
        desktopPane.add(janela);
        this.setContentPane(desktopPane);
    }//GEN-LAST:event_btnMenuClubeActionPerformed

    private void mniSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mniSairActionPerformed

    private void btnMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnMenuSairActionPerformed

    private void mniUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniUsuariosActionPerformed
        // TODO add your handling code here:
        CadastroUsuario janela = new CadastroUsuario();
        janela.setVisible(true);
        
        desktopPane.add(janela);
        this.setContentPane(desktopPane);
    }//GEN-LAST:event_mniUsuariosActionPerformed

    private void mniSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSociosActionPerformed
        // TODO add your handling code here:
        CadastroSocios janela = new CadastroSocios();
        janela.setVisible(true);
        
        desktopPane.add(janela);
        this.setContentPane(desktopPane);
    }//GEN-LAST:event_mniSociosActionPerformed

    private void mniContasPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniContasPagarActionPerformed
        // TODO add your handling code here:
        ContasPagar janela = new ContasPagar();
        janela.setVisible(true);
        
        desktopPane.add(janela);
        this.setContentPane(desktopPane);
    }//GEN-LAST:event_mniContasPagarActionPerformed

    private void mniContasReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniContasReceberActionPerformed
        // TODO add your handling code here:
        ContasReceber janela = new ContasReceber();
        janela.setVisible(true);
        
        desktopPane.add(janela);
        this.setContentPane(desktopPane);
    }//GEN-LAST:event_mniContasReceberActionPerformed

    private void btnMenuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuUsuariosActionPerformed
        // TODO add your handling code here:
        CadastroUsuario janela = new CadastroUsuario();
        janela.setVisible(true);
        
        desktopPane.add(janela);
        this.setContentPane(desktopPane);
    }//GEN-LAST:event_btnMenuUsuariosActionPerformed

    private void bntMenuSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMenuSociosActionPerformed
        // TODO add your handling code here:
        CadastroSocios janela = new CadastroSocios();
        janela.setVisible(true);
        
        desktopPane.add(janela);
        this.setContentPane(desktopPane);
    }//GEN-LAST:event_bntMenuSociosActionPerformed

    private void btnMenuContasPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuContasPagarActionPerformed
        // TODO add your handling code here:
        ContasPagar janela = new ContasPagar();
        janela.setVisible(true);
        
        desktopPane.add(janela);
        this.setContentPane(desktopPane);
    }//GEN-LAST:event_btnMenuContasPagarActionPerformed

    private void btnMenuContasReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuContasReceberActionPerformed
        // TODO add your handling code here:
        ContasReceber janela = new ContasReceber();
        janela.setVisible(true);
        
        desktopPane.add(janela);
        this.setContentPane(desktopPane);
    }//GEN-LAST:event_btnMenuContasReceberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntMenuSocios;
    private javax.swing.JButton btnMenuClube;
    private javax.swing.JButton btnMenuContasPagar;
    private javax.swing.JButton btnMenuContasReceber;
    private javax.swing.JButton btnMenuSair;
    private javax.swing.JButton btnMenuUsuarios;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mniClube;
    private javax.swing.JMenuItem mniContasPagar;
    private javax.swing.JMenuItem mniContasReceber;
    private javax.swing.JMenuItem mniSair;
    private javax.swing.JMenuItem mniSobre;
    private javax.swing.JMenuItem mniSocios;
    private javax.swing.JMenuItem mniUsuarios;
    private javax.swing.JMenu mnuRelatorios;
    // End of variables declaration//GEN-END:variables
}
