/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.utfpr.view;

import br.edu.utfpr.main.Main;
import br.edu.utfpr.model.Categorias_Socios;
import br.edu.utfpr.model.Empresa;
import java.util.List;
import javax.persistence.TypedQuery;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jeferson.scarsi
 */
public class CategoriaSocios extends javax.swing.JInternalFrame {
    private DefaultTableModel modeloTabela = new DefaultTableModel();
    private Categorias_Socios categoriaSelecionada;
    private Object getId;

    /**
     * Creates new form cadastroUsuario
     */
    public CategoriaSocios() {
        initComponents();
        
        modeloTabela = (DefaultTableModel) tblCategoria.getModel();
        carregarListaCategorias();  
        txtDescricao.setEditable(false);
        ftxValor.setEditable(false);
        
    }
    
    private void carregarListaCategorias(){
        //Remover linhas existentes
        while(tblCategoria.getRowCount() > 0){
            modeloTabela.removeRow(0);
        }
        
        String jpql = "select cs from Categorias_Socios cs";
        TypedQuery query = Main.em.createQuery(jpql, Categorias_Socios.class);
        
        List<Categorias_Socios> lista = query.getResultList();
        for (Categorias_Socios cs : lista){
            Object row[] = {
                cs.getIdcategoria(),
                cs.getDescrcategoria(),
                cs.getValor(),
                cs.isFlagativo()
            };
            
            modeloTabela.addRow(row);
        }
        
    }
    
    private void novaCategoria(){
        txtCodCategoria.setText("");
        txtDescricao.setText("");
        ftxValor.setValue(0);
        chkFlagAtivo.setSelected(true);
        
        tblCategoria.clearSelection();
        categoriaSelecionada = null;        
    }
    
    private boolean validarCampos(){
        
        if (txtDescricao.getText().trim().length() == 0 ){
            JOptionPane.showMessageDialog(this, "Campo Descrição é obrigatório");
            return false;
        }
        
        if (ftxValor.getText().trim().length() == 0 ){
            JOptionPane.showMessageDialog(this, "Campo valor é obrigatório.");
        }
        
        return true;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCodCategoria = new javax.swing.JLabel();
        txtCodCategoria = new javax.swing.JTextField();
        lblDescricao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        tbnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        chkFlagAtivo = new javax.swing.JCheckBox();
        lblDescricao1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCategoria = new javax.swing.JTable();
        ftxValor = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Categoria de Usuários");

        lblCodCategoria.setText("Cod. Categoria:");

        txtCodCategoria.setEditable(false);

        lblDescricao.setText("Descrição:");

        jToolBar1.setRollover(true);

        tbnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens-24px/botao-adicionar.png"))); // NOI18N
        tbnNovo.setFocusable(false);
        tbnNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbnNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnNovoActionPerformed(evt);
            }
        });
        jToolBar1.add(tbnNovo);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens-24px/disquete.png"))); // NOI18N
        btnSalvar.setFocusable(false);
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSalvar);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens-24px/lapis.png"))); // NOI18N
        btnEditar.setFocusable(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEditar);

        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens-24px/excluir.png"))); // NOI18N
        btnRemover.setFocusable(false);
        btnRemover.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRemover.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRemover);

        chkFlagAtivo.setText("Ativo");
        chkFlagAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFlagAtivoActionPerformed(evt);
            }
        });

        lblDescricao1.setText("Valor:");

        tblCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cod.", "Descrição", "Valor", "Flag Ativo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Float.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCategoria);
        if (tblCategoria.getColumnModel().getColumnCount() > 0) {
            tblCategoria.getColumnModel().getColumn(0).setMaxWidth(50);
            tblCategoria.getColumnModel().getColumn(1).setMaxWidth(350);
            tblCategoria.getColumnModel().getColumn(2).setMaxWidth(100);
            tblCategoria.getColumnModel().getColumn(3).setMaxWidth(75);
        }

        ftxValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCodCategoria)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescricao)
                            .addComponent(txtCodCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftxValor)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkFlagAtivo)
                                    .addComponent(lblDescricao1))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCodCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkFlagAtivo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCodCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDescricao))
                    .addComponent(lblDescricao1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxValor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnNovoActionPerformed
        novaCategoria();
        
        txtDescricao.setEditable(true);
        ftxValor.setEditable(true);
    }//GEN-LAST:event_tbnNovoActionPerformed

    private void chkFlagAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFlagAtivoActionPerformed
        
    }//GEN-LAST:event_chkFlagAtivoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        boolean novo = false;
        
        if (validarCampos() == false){
            return;
        }
        
        if (categoriaSelecionada == null){
            novo = true;
            categoriaSelecionada = new Categorias_Socios();
        }
        
        categoriaSelecionada.setDescrcategoria(txtDescricao.getText());
        
        
        String valorString = String.valueOf(ftxValor.getText());
        categoriaSelecionada.setValor(Double.parseDouble(valorString));
        categoriaSelecionada.setFlagativo(chkFlagAtivo.isSelected());
        
        Main.em.getTransaction().begin();
        if (novo){
            Main.em.persist(categoriaSelecionada);
        }else {
            Main.em.persist(categoriaSelecionada);
        }
        Main.em.getTransaction().commit();
        
        novaCategoria();
        txtDescricao.setEditable(false);
        ftxValor.setEditable(false);
        chkFlagAtivo.setSelected(false);
        
        carregarListaCategorias();  
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (tblCategoria.getSelectedRow() != -1){
            Long id = (Long) modeloTabela.getValueAt(tblCategoria.getSelectedRow(), 0);
            
            categoriaSelecionada = Main.em.find(Categorias_Socios.class, id);
            txtCodCategoria.setText(categoriaSelecionada.getIdcategoria().toString());
            txtDescricao.setText(categoriaSelecionada.getDescrcategoria());
            this.ftxValor.setText(String.valueOf(categoriaSelecionada.getValor()));
            this.chkFlagAtivo.setSelected(categoriaSelecionada.isFlagativo());
            
            txtDescricao.setEditable(true);
            ftxValor.setEditable(true);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        if (tblCategoria.getSelectedRow() != -1){
            Long id = (Long) modeloTabela.getValueAt(tblCategoria.getSelectedRow(), 0);
            categoriaSelecionada = Main.em.find(Categorias_Socios.class, id);
            
            int result = JOptionPane.showConfirmDialog(this, "Deseja remover a categoria " + categoriaSelecionada.getDescrcategoria()+ "?", "Remoção", JOptionPane.YES_NO_OPTION);
            
            if (result == JOptionPane.YES_OPTION){
                Main.em.getTransaction().begin();
                Main.em.remove(categoriaSelecionada);
                Main.em.getTransaction().commit();

                carregarListaCategorias();
                novaCategoria();
                
                txtDescricao.setEditable(false);
                ftxValor.setEditable(false);
                chkFlagAtivo.setSelected(false);
            }            
        }else{
            JOptionPane.showMessageDialog(this, "Selecione um registro para remover.");
        }
    }//GEN-LAST:event_btnRemoverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox chkFlagAtivo;
    private javax.swing.JFormattedTextField ftxValor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblCodCategoria;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblDescricao1;
    private javax.swing.JTable tblCategoria;
    private javax.swing.JButton tbnNovo;
    private javax.swing.JTextField txtCodCategoria;
    private javax.swing.JTextField txtDescricao;
    // End of variables declaration//GEN-END:variables
}
