/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.utfpr.view;

import br.edu.utfpr.main.Main;
import java.beans.PropertyVetoException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.TypedQuery;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jeferson.scarsi
 */
public class Financeiro extends javax.swing.JInternalFrame {
    private DefaultTableModel modeloTabela = new DefaultTableModel();
    /**
     * Creates new form ContasPagar
     */
    public Financeiro() {
        initComponents();
        try {
            this.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Financeiro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void novoTitulo(){
        txtCodClienteLanc.setEditable(true);
        txtNomeFantasiaLanc.setEditable(true);
        ftxDataCompetenciaLanc.setEditable(true);
        
        Date date = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("ddMMyyyy");
        ftxDataCompetenciaLanc.setText(formatter.format(date).toString());
        ftxDataVencLanc.setText(formatter.format(date).toString());
        
        ftxValorBrutoLanc.setEditable(true);
        ftxValorDescLanc.setEditable(true);
        ftxValorAcrescimoLanc.setEditable(true);
        
        //tblEmpresas.clearSelection();
        //empresaSelecionada = null;        
    }
    
    /*private void carregarListaEmpresas(){
        //Remover linhas existentes
        while(tblTituloPesq.getRowCount() > 0){
            modeloTabela.removeRow(0);
        }
        
        String jpql = "select cp from ContasPagar cp";
        TypedQuery query = Main.em.createQuery(jpql, Financeiro.class);
        
        List<Financeiro> lista = query.getResultList();
        for (Financeiro cp : lista){
            Object row[] = {
                
            };
            
            modeloTabela.addRow(row);
        }
        
    }*/
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        tbpFinanceiro = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodSocioPesq = new javax.swing.JTextField();
        lblNumTitulo = new javax.swing.JLabel();
        txtNumTituloPesq = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTituloPesq = new javax.swing.JTable();
        optContasPagarPesq = new javax.swing.JRadioButton();
        optContasReceberPesq = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        lblInfPagLanc = new javax.swing.JLabel();
        lblParcela = new javax.swing.JLabel();
        lblNumTituloLanc = new javax.swing.JLabel();
        txtNumTituloLanc = new javax.swing.JTextField();
        txtCodClienteLanc = new javax.swing.JTextField();
        lblNomeFantasiaLanc = new javax.swing.JLabel();
        txtNomeFantasiaLanc = new javax.swing.JTextField();
        lblDataCompLanc = new javax.swing.JLabel();
        optContasPagarLanc = new javax.swing.JRadioButton();
        optContasReceberLanc = new javax.swing.JRadioButton();
        lblDataVencLanc = new javax.swing.JLabel();
        lblValorBrutoLanc = new javax.swing.JLabel();
        lblValorDescLanc = new javax.swing.JLabel();
        lblValorAcrescimoLanc = new javax.swing.JLabel();
        lblValorLiqLanc = new javax.swing.JLabel();
        lblDadosCliente = new javax.swing.JLabel();
        lblCodClienteLanc = new javax.swing.JLabel();
        cmbParcela = new javax.swing.JComboBox<>();
        lblFormaPagLanc = new javax.swing.JLabel();
        ftxDataCompetenciaLanc = new javax.swing.JFormattedTextField();
        ftxDataVencLanc = new javax.swing.JFormattedTextField();
        ftxValorBrutoLanc = new javax.swing.JFormattedTextField();
        ftxValorDescLanc = new javax.swing.JFormattedTextField();
        ftxValorAcrescimoLanc = new javax.swing.JFormattedTextField();
        ftxValorLiqLanc = new javax.swing.JFormattedTextField();
        jToolBar1 = new javax.swing.JToolBar();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Financeiro");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cód. Sócios: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, -1, -1));
        jPanel1.add(txtCodSocioPesq, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 12, 130, -1));

        lblNumTitulo.setText("Num. Título:");
        jPanel1.add(lblNumTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 46, -1, -1));
        jPanel1.add(txtNumTituloPesq, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 43, 130, -1));

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 11, 83, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 42, 83, -1));

        tblTituloPesq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód. Título", "Cód. Sócio", "Nome Sócio", "Num. Sequencia", "Valor Bruto", "Valor Desconto", "Valor Acrescimo", "Valor Líquido"
            }
        ));
        jScrollPane1.setViewportView(tblTituloPesq);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 71, 736, 191));

        buttonGroup1.add(optContasPagarPesq);
        optContasPagarPesq.setSelected(true);
        optContasPagarPesq.setText("Contas a Pagar");
        jPanel1.add(optContasPagarPesq, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 11, -1, -1));

        buttonGroup1.add(optContasReceberPesq);
        optContasReceberPesq.setText("Contas a Receber");
        jPanel1.add(optContasReceberPesq, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 42, -1, -1));

        tbpFinanceiro.addTab("Pesquisar", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInfPagLanc.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblInfPagLanc.setText("Informações de Pagamento");
        jPanel2.add(lblInfPagLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        lblParcela.setText("Parcela:");
        jPanel2.add(lblParcela, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 110, -1));

        lblNumTituloLanc.setText("Num. Título:");
        jPanel2.add(lblNumTituloLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 37, -1, -1));

        txtNumTituloLanc.setEditable(false);
        jPanel2.add(txtNumTituloLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 57, 75, -1));

        txtCodClienteLanc.setEditable(false);
        jPanel2.add(txtCodClienteLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 57, 75, -1));

        lblNomeFantasiaLanc.setText("Nome Fantasia:");
        jPanel2.add(lblNomeFantasiaLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 83, -1, -1));

        txtNomeFantasiaLanc.setEditable(false);
        jPanel2.add(txtNomeFantasiaLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 230, -1));

        lblDataCompLanc.setText("Data Competencia:");
        jPanel2.add(lblDataCompLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 95, -1));

        buttonGroup2.add(optContasPagarLanc);
        optContasPagarLanc.setSelected(true);
        optContasPagarLanc.setText("Contas a Pagar");
        optContasPagarLanc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                optContasPagarLancKeyReleased(evt);
            }
        });
        jPanel2.add(optContasPagarLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 53, -1, -1));

        buttonGroup2.add(optContasReceberLanc);
        optContasReceberLanc.setText("Contas a Receber");
        jPanel2.add(optContasReceberLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 53, -1, -1));

        lblDataVencLanc.setText("Data Vencimento:");
        jPanel2.add(lblDataVencLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 83, -1, -1));

        lblValorBrutoLanc.setText("Valor Bruto:");
        jPanel2.add(lblValorBrutoLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 75, -1));

        lblValorDescLanc.setText("Valor Desconto:");
        jPanel2.add(lblValorDescLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 92, -1));

        lblValorAcrescimoLanc.setText("Valor Acréscimo:");
        jPanel2.add(lblValorAcrescimoLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 92, -1));

        lblValorLiqLanc.setText("Valor Líquido:");
        jPanel2.add(lblValorLiqLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 92, -1));

        lblDadosCliente.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblDadosCliente.setText("Dados do Cliente");
        jPanel2.add(lblDadosCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        lblCodClienteLanc.setText("Cód. Cliente:");
        jPanel2.add(lblCodClienteLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 37, 75, -1));

        cmbParcela.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cmbParcela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmbParcelaKeyReleased(evt);
            }
        });
        jPanel2.add(cmbParcela, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 100, -1));

        lblFormaPagLanc.setText("Forma de Pagamento:");
        jPanel2.add(lblFormaPagLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 110, -1));

        ftxDataCompetenciaLanc.setEditable(false);
        try {
            ftxDataCompetenciaLanc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(ftxDataCompetenciaLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 120, -1));

        ftxDataVencLanc.setEditable(false);
        try {
            ftxDataVencLanc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(ftxDataVencLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 110, -1));

        ftxValorBrutoLanc.setEditable(false);
        jPanel2.add(ftxValorBrutoLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 110, -1));

        ftxValorDescLanc.setEditable(false);
        jPanel2.add(ftxValorDescLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 110, -1));

        ftxValorAcrescimoLanc.setEditable(false);
        jPanel2.add(ftxValorAcrescimoLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 120, -1));

        ftxValorLiqLanc.setEditable(false);
        ftxValorLiqLanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxValorLiqLancActionPerformed(evt);
            }
        });
        jPanel2.add(ftxValorLiqLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 110, -1));

        tbpFinanceiro.addTab("Lançamentos", jPanel2);

        jToolBar1.setRollover(true);

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens-24px/botao-adicionar.png"))); // NOI18N
        btnNovo.setFocusable(false);
        btnNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNovo);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens-24px/disquete.png"))); // NOI18N
        btnSalvar.setFocusable(false);
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnSalvar);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens-24px/lapis.png"))); // NOI18N
        btnEditar.setFocusable(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEditar);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens-24px/excluir.png"))); // NOI18N
        btnExcluir.setFocusable(false);
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnExcluir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpFinanceiro)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(tbpFinanceiro, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cmbParcelaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbParcelaKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbParcelaKeyReleased

    private void optContasPagarLancKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_optContasPagarLancKeyReleased
        // TODO add your handling code here:        
    }//GEN-LAST:event_optContasPagarLancKeyReleased

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        novoTitulo();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void ftxValorLiqLancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxValorLiqLancActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxValorLiqLancActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmbParcela;
    private javax.swing.JFormattedTextField ftxDataCompetenciaLanc;
    private javax.swing.JFormattedTextField ftxDataVencLanc;
    private javax.swing.JFormattedTextField ftxValorAcrescimoLanc;
    private javax.swing.JFormattedTextField ftxValorBrutoLanc;
    private javax.swing.JFormattedTextField ftxValorDescLanc;
    private javax.swing.JFormattedTextField ftxValorLiqLanc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblCodClienteLanc;
    private javax.swing.JLabel lblDadosCliente;
    private javax.swing.JLabel lblDataCompLanc;
    private javax.swing.JLabel lblDataVencLanc;
    private javax.swing.JLabel lblFormaPagLanc;
    private javax.swing.JLabel lblInfPagLanc;
    private javax.swing.JLabel lblNomeFantasiaLanc;
    private javax.swing.JLabel lblNumTitulo;
    private javax.swing.JLabel lblNumTituloLanc;
    private javax.swing.JLabel lblParcela;
    private javax.swing.JLabel lblValorAcrescimoLanc;
    private javax.swing.JLabel lblValorBrutoLanc;
    private javax.swing.JLabel lblValorDescLanc;
    private javax.swing.JLabel lblValorLiqLanc;
    private javax.swing.JRadioButton optContasPagarLanc;
    private javax.swing.JRadioButton optContasPagarPesq;
    private javax.swing.JRadioButton optContasReceberLanc;
    private javax.swing.JRadioButton optContasReceberPesq;
    private javax.swing.JTable tblTituloPesq;
    private javax.swing.JTabbedPane tbpFinanceiro;
    private javax.swing.JTextField txtCodClienteLanc;
    private javax.swing.JTextField txtCodSocioPesq;
    private javax.swing.JTextField txtNomeFantasiaLanc;
    private javax.swing.JTextField txtNumTituloLanc;
    private javax.swing.JTextField txtNumTituloPesq;
    // End of variables declaration//GEN-END:variables
}
